# Site
title: Athena
subtitle: Beautful Hexo Theme
description:
author: Frye Lee
language:

# Default post title
default_post_title: Halo

#Date Format
date_format: YYYY-MM-DD

# Menu
menu:
  Home: /
  About: /about
rss: /atom.xml

# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config 
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: true #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: false # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code

# Comment. 
comments:
  # Disqus comment
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: 
 